/**
 * @file act_stats.h
 * @brief Parser for ACT normalization and SO-101 calibration stats.
 */

#ifndef ONNX_INFERENCE_ACT_CPP_UTILS_ACT_STATS_H_
#define ONNX_INFERENCE_ACT_CPP_UTILS_ACT_STATS_H_

#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

struct MotorCalib {
    std::string name;
    int id = 0;
    int drive_mode = 0;
    int range_min = 0;
    int range_max = 4095;
    std::string norm_mode = "DEGREES";
};

struct ActStats {
    std::vector<std::string> cam_names;
    int img_c = 3, img_h = 480, img_w = 640;
    int state_dim = 6, action_dim = 6;
    int chunk_size = 100, n_action_steps = 100;
    std::vector<std::string> motor_order;
    std::vector<float> state_mean, state_std;
    std::vector<float> action_mean, action_std;
    std::map<std::string, std::vector<float>> image_mean;
    std::map<std::string, std::vector<float>> image_std;
    std::vector<MotorCalib> calib;
};

inline std::vector<float> ParseFloats(std::istringstream& ss) {
    std::vector<float> v;
    float x;
    while (ss >> x) v.push_back(x);
    return v;
}

/**
 * @brief Parse an ACT stats text file generated by tools/export_norm_stats.py.
 *
 * @param path Path to act_norm_stats.txt.
 * @return Parsed normalization, camera, motor order, and calibration metadata.
 * @throws std::runtime_error if the stats file cannot be opened.
 */
inline ActStats ParseActStats(const std::string& path) {
    std::ifstream f(path);
    if (!f) throw std::runtime_error("cannot open stats file: " + path);
    ActStats s;
    std::map<std::string, MotorCalib> calib_by_name;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ss(line);
        std::string key;
        ss >> key;
        if (key == "cam_names") {
            std::string n;
            while (ss >> n) s.cam_names.push_back(n);
        } else if (key == "img_chw") {
            ss >> s.img_c >> s.img_h >> s.img_w;
        } else if (key == "state_dim") {
            ss >> s.state_dim;
        } else if (key == "action_dim") {
            ss >> s.action_dim;
        } else if (key == "chunk_size") {
            ss >> s.chunk_size;
        } else if (key == "n_action_steps") {
            ss >> s.n_action_steps;
        } else if (key == "motor_order") {
            std::string n;
            while (ss >> n) s.motor_order.push_back(n);
        } else if (key == "state_mean") {
            s.state_mean = ParseFloats(ss);
        } else if (key == "state_std") {
            s.state_std = ParseFloats(ss);
        } else if (key == "action_mean") {
            s.action_mean = ParseFloats(ss);
        } else if (key == "action_std") {
            s.action_std = ParseFloats(ss);
        } else if (key.rfind("image_mean.", 0) == 0) {
            s.image_mean[key.substr(std::strlen("image_mean."))] = ParseFloats(ss);
        } else if (key.rfind("image_std.", 0) == 0) {
            s.image_std[key.substr(std::strlen("image_std."))] = ParseFloats(ss);
        } else if (key == "calib") {
            MotorCalib c;
            ss >> c.name;
            std::string tok;
            while (ss >> tok) {
                if (tok == "id") ss >> c.id;
                else if (tok == "drive_mode") ss >> c.drive_mode;
                else if (tok == "range_min") ss >> c.range_min;
                else if (tok == "range_max") ss >> c.range_max;
                else if (tok == "norm_mode") ss >> c.norm_mode;
            }
            calib_by_name[c.name] = c;
        }
    }
    for (const auto& m : s.motor_order) {
        auto it = calib_by_name.find(m);
        if (it != calib_by_name.end()) s.calib.push_back(it->second);
    }
    return s;
}

#endif  // ONNX_INFERENCE_ACT_CPP_UTILS_ACT_STATS_H_
